Automatically generate a "signature" when CMake is invoked
njoy/metaconfigure pull request #20
Opened 2018-09-27 22:38 UTC by jlconlin

This is a request that customers have made so that they know exactly which version of all the dependencies they have when it is built.

2018-10-02 21:27 UTC, jlconlin commented
This is ready to go and adds ability to do `configure_file`.

2018-10-02 21:27 UTC, jlconlin commented
Someone please review.

2018-10-11 21:00 UTC, jlconlin commented on cmake.py
> +    if state["signature"]:
Use `if state.get("signature")` instead. This will avoid `KeyError` issues.

2018-10-11 21:00 UTC, jlconlin commented on cmake.py
> +    contents = textwrap.dedent(
Wrap this in a block that ensures it is not a subproject.

2018-10-11 21:00 UTC, jlconlin commented on cmake.py
> +                            "${{CMAKE_CURRENT_BINARY_DIR}}/{hpp}" )
Add `@ONLY` to ensure that it only replaces the @VARIABLE@ stuff.

2018-10-11 21:02 UTC, jlconlin reviewed
asdfasd

2018-10-11 21:02 UTC, jlconlin commented on signature.py
> +    for subproject in os.listdir( "subprojects" ):
Add `try` block to catch if `subprojects` doesn't exist as subdirectory.

2018-10-11 21:19 UTC, jlconlin commented
Change description_generate to add configure file extensions

2018-10-11 21:20 UTC, jlconlin commented
@apmccartney Add signature.json to install part of CMake.

2018-10-11 21:44 UTC, whaeck requested changes

2018-10-11 21:44 UTC, whaeck commented on cmake.py
> +                message( FATAL_ERROR "Python interpeter installation was not found." )
There's a typo here: interpeter

2018-10-16 19:34 UTC, apmccartney approved these changes
Verified comments addressed

2018-10-16 21:08 UTC, merged